### ISSUE TITLE
Variable case fixer for class attributes breaks code

### ISSUE THREAD

**Issue by simbig** [mll-lab/php-cs-fixer-config#4]
In case the fixed variable is a class attribute fixer will only fix the attribute definition but not the usage with "$this->"-context:

### How to reproduce
add the following test:
```
[
     '<?php class Bar {public $fooBar = 1; public function test() {$this->fooBar = 0;}} ?>',
     '<?php class Bar {public $foo_bar = 1; public function test() {$this->foo_bar = 0;}} ?>',
],
```
this will return the following failure:
```
--- Expected
+++ Actual
@@ @@
-'<?php class Bar {public $fooBar = 1; public function test() {$this->fooBar = 0;}} ?>'
+'<?php class Bar {public $fooBar = 1; public function test() {$this->foo_bar = 0;}} ?>'
```

**Comment by spawnia** [comment]
We also have to consider `<?php class Foo { public $foo_bar; } (new Foo)->foo_bar;`.

**Comment by spawnia** [comment]
I removed this fixer for now, as it is incompatible with the latest v3, I think we are better off waiting for official support.
